= Ansible playbook to install BIND on Ubuntu Server

The playbook will perform the installation tasks described below. 
Rename the .example playbook to .yaml and edit the file with your host value. 
You will need ssh access to the ubuntu server. The sudo password has to be given in the vars/dns_vars.yaml file.
Rename this file also from .example to .yaml. +

== DNS server installation on Ubuntu Server

* sudo apt-get update
* sudo apt-get upgrade
* sudo apt-get dist-upgrade

== Install BIND +
sudo apt-get install bind9 bind9utils bind9-doc +

== use caching server +

    /etc/bind/named.conf.options  
    forwarders { 
     8.8.8.8;
     };
    sudo systemctl restart bind9 

== Configure primary DNS server +
Edit ‘/etc/bind/named.conf’ using any editor of your choice:

    sudo nano /etc/bind/named.conf

This file should have the following lines in it. If the lines are not there, just add them.

    include "/etc/bind/named.conf.options";
    include "/etc/bind/named.conf.local";
    include "/etc/bind/named.conf.default-zones";

Before these lines add the acl that allows 10.10.0.0/16 to query the dns server +

    acl "trusted" {
    10.10.0.0/16;
    localhost;
    localnets;
    };

Add this acl to /etc/bind/named.conf.options in the 'options' section

    options {
            allow-query { any; };
            allow-recursion { trusted; };
            allow-query-cache { trusted; };
    };

== Add Forward and reverse zone files +

    sudo nano /etc/bind/named.conf.local
    zone "example.com" {
            type master;
            file "/etc/bind/for.example.com.org";
     };
    zone "0.10.10.in-addr.arpa" {
            type master;
            file "/etc/bind/rev0.example.com.org";
     };
    zone "1.10.10.in-addr.arpa" {
            type master;
            file "/etc/bind/rev1.example.com.org";
     };

=== Create forward zone file

    vim /etc/bind/for.example.com.org

    $TTL 3600
    @   IN  SOA     example.com. root.example.com. (
            2019032301  ;Serial
            3600        ;Refresh    
            1800        ;Retry
            604800      ;Expire
            300         ;Minimum TTL
    )
    ; DNS Servers
    @               IN      NS      ns1.example.com.
    ; MX Records
                    IN      MX 10   mx.example.com.
                    IN      MX 20   relay.transip.nl.
    ; Machine Names
    @               IN      A       1.1.1.1 
    @               IN      AAAA    2001::1
    localhost       IN      A       127.0.0.1
    example1        IN      A       10.10.0.4
    example2        IN      A       10.10.1.5
    ; Aliases
    example3        IN      CNAME   example1

=== Create reverse zone files

    vim /etc/bind/rev0.example.com.org
    $TTL 3600
    @   IN  SOA         example.com. root.example.com. (
            2019032301  ;Serial
            3600        ;Refresh
            1800        ;Retry
            604800      ;Expire
            300         ;Minimum TTL
            )
    @       IN  NS      ns1.example.com
    4       IN  PTR     example1.example.com.

    vim /etc/bind/rev1.example.com.org
    $TTL 3600
    @   IN  SOA         ns1.example.com. root.example.com. (
            2019032301  ;Serial
            3600        ;Refresh
            1800        ;Retry
            604800      ;Expire
            300         ;Minimum TTL
            )
    @       IN  NS      ns1.example.com.
    5       IN  PTR     example2.example.com.

== Fix permissions

    sudo chmod -R 755 /etc/bind

    sudo chown -R bind:bind /etc/bind

== Check configuration

    sudo named-checkconf /etc/bind/named.conf

    sudo named-checkconf /etc/bind/named.conf.local

    sudo named-checkzone example.com /etc/bind/for.example.com.org

    sudo named-checkzone example.com /etc/bind/rev.example.com.org

The first two should output nothing. The last two should give back *"OK"*

Restart server with: [.underline]*sudo systemctl restart bind9*
